### ISSUE TITLE
Question: firewalls per role

### ISSUE THREAD

**Issue by haf** [gdm85/docker-fw#3]
Hi,

This is a question of a higher-level pattern. I understand docker-fw easily gives access to firewall configuration for ip+port+protocol, but what if I have a consul setup together with registrator and all containers are tagged with their respective services/roles? Is there an easy way to bind the real-time health checks of consul and registrator together with docker-fw to automatically add/remove firewall rules when containers are added and removed?

**Comment by gdm85** [comment]
@haf premise: I am not familiar with consul, although I've read about it I never managed to give it a try. Same for registrator.

I think what you are looking for are hook features in Docker and the other middleware you mentioned. For example, give a look to https://github.com/ClusterHQ/powerstrip (suggested to me by @cpuguy83 some time ago).
