### ISSUE TITLE
Building docker-fw using build.sh fails

### ISSUE THREAD

**Issue by geertn** [gdm85/docker-fw#4]
[root@monitor ~]# git clone https://github.com/gdm85/docker-fw.git
Cloning into 'docker-fw'...
remote: Counting objects: 208, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 208 (delta 59), reused 54 (delta 54), pack-reused 140
Receiving objects: 100% (208/208), 69.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (135/135), done.
[root@monitor ~]# cd docker-fw/
[root@monitor docker-fw]# ./build.sh 
package github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar
    imports github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar
    imports github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar: cannot find package "github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar" in any of:
    /usr/lib/golang/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar (from $GOROOT)
    /root/goroot/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar (from $GOPATH)
[root@monitor docker-fw]#

**Comment by gdm85** [comment]
should be fixed by d9cee19989ead67e6107740869ba9c13d4ff6096
if not, please comment and I'll reopen this issue
